### PR TITLE
fix: get_purl now deals with missing ns properly

### LINKED ISSUE #1456: allow filtering component analysis by base purl
In a typical Product Security workflow a security analyst would look for base purls matching a vulnerability report, then try to find all the (latest) products with that base purl. In order to support that work flow we should be able to filter by base_purl and arch.

Today we can use a partial match on purl to do a similar thing, but it returns too many results, which then need to be filtered out by the search client. It would be more efficient to only return matching base purls and archs.

For example:

`api/v2/analysis/component?q=purl~pkg:rpm/redhat/webkit2gtk3`

Returns the expected result, like:

`pkg:rpm/redhat/webkit2gtk`

but also purls other packages with other trailing characters, (binary RPMS) eg:

`pkg:rpm/redhat/webkit2gtk3-debuginfo`

Even if the base_purl matched exactly, there are often multiple arch for the same result, eg:

`pkg:rpm/redhat/webkit2gtk3@2.42.5-1.el9?arch=src`
`pkg:rpm/redhat/webkit2gtk3@2.42.5-1.el9?arch=aarch64`

so being able to filter by arch would also be nice:

`api/v2/analysis/component?q=purl~pkg:rpm/redhat/webkit2gtk3&arch=src`

In fact, being able to filter to arch would probably give us what we need most of the time, even without filtering by base_purl.

### PR DESCRIPTION
**Pull request by jcrossley3**
Fixes #1456

We're gonna need get_purl to work properly to migrate the data for #1440 anyway.

### CODE REVIEW

File: modules/analysis/src/endpoints/tests/mod.rs [hunk 1]
```diff
@@ -422,6 +419,38 @@ async fn find_component_by_query(ctx: &TrustifyContext) -> Result<(), anyhow::Er
...
+    ] {
+        assert!(query(each).await.contains_subset(json!({
+            "items": [{
+                "purl": [ PURL ],
+            }]
+        })));
+    }
+
+    Ok(())
+}
```
Comment (jcrossley3) [inline modules/analysis/src/endpoints/tests/mod.rs:452]: @jasinner thanks for the unit test! :smile:

**Review by JimFuller-RedHat — APPROVED** [review]
LGTM!
